<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">    
    <span class="f-left">
		<?php /* @escapeNotVerified */ echo $block->getCopyright() ?>		
	</span>						
</small>

<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
	var s1=document.createElement("script"),
	s0=document.getElementsByTagName("script")[0];
	s1.async=true;
	s1.src='https://embed.tawk.to/5a9d138fd7591465c7084068/default';
	s1.charset='UTF-8';
	s1.setAttribute('crossorigin','*');
	s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->

<script type="text/javascript">
require([
        'jquery',
        'jquery/jquery.cookie',
    ], function($) {
        if (!window.matchMedia('(max-width: 1024px)').matches) {
            Tawk_API.onLoad = function(){
                if($.cookie('tawkonlinechat') == null) 
                {
                    Tawk_API.toggle();
                }
                var date = new Date();
                var minutes = 1440;
                date.setTime(date.getTime() + (minutes * 60 * 1000));
                $.cookie('tawkonlinechat', '1', {expires: date}); // Set Cookie Expiry Time        
            };
        }

        /* Open quick chat box when click on homepage "Quickchat Feature" text under welcome text */
        $(".home-quickchat").on( "click", function() {
          Tawk_API.toggle();
        });
    });
</script>